# Generated by Django 5.0.7 on 2024-07-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animesite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animetitle',
            name='image',
            field=models.ImageField(upload_to='static'),
        ),
    ]
