# Generated by Django 5.0.7 on 2024-07-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animesite', '0006_alter_animetitle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animetitle',
            name='image',
        ),
        migrations.AddField(
            model_name='animetitle',
            name='image_link',
            field=models.URLField(null=True),
        ),
    ]
