# Generated by Django 5.0.7 on 2024-07-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animesite', '0007_remove_animetitle_image_animetitle_image_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
