# Generated by Django 5.0.7 on 2024-07-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animesite', '0008_animeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeuser',
            name='favourite_anime',
            field=models.TextField(null=True),
        ),
    ]
