# Generated by Django 5.0.7 on 2024-07-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animesite', '0009_animeuser_favourite_anime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeuser',
            name='favourite_anime',
            field=models.TextField(default=''),
        ),
    ]
